import React, { useState, useEffect, useCallback } from 'react';
import './src/styles/theme.css';
import FileExplorer from './components/FileExplorer';
import CodeEditor from './components/CodeEditor';
import Preview from './components/Preview';
import Terminal from './components/Terminal';
import AgentStatus from './components/AgentStatus';
import TestGenerator from './components/TestGenerator';
import { SimulationState, FileNode, LogEntry, ChatMessage, AgentRole } from './types';
import * as ai from './lib/gemini';
import
  {
    FlaskConical,
    Code2,
    Sparkles,
    Search,
    Bell,
    LayoutDashboard,
    Cpu,
    Settings,
    X
  } from 'lucide-react';

const INITIAL_FILES: FileNode[] = [
  {
    name: 'src',
    type: 'folder',
    isOpen: true,
    children: [
      { name: 'App.tsx', type: 'file', content: '// Enter a prompt to generate code...' },
      { name: 'index.tsx', type: 'file', content: 'import React from "react";\nimport ReactDOM from "react-dom/client";\nimport App from "./App";\n\nconst root = ReactDOM.createRoot(document.getElementById("root"));\nroot.render(<App />);' },
    ]
  },
  { name: 'package.json', type: 'file', content: '{\n  "dependencies": {\n    "react": "^18.2.0",\n    "lucide-react": "^0.363.0"\n  }\n}' },
  { name: 'README.md', type: 'file', content: '# My Agentic App\n\nGenerated by Agentic Studio Pro.' },
];

function App ()
{
  const [ state, setState ] = useState<SimulationState>( {
    status: 'idle',
    activeAgent: 'idle',
    currentFile: 'App.tsx',
    files: INITIAL_FILES,
    logs: [],
    messages: [],
    previewUrl: 'http://localhost:3000/preview',
    codeContent: '',
    previewContent: null,
    iteration: 0,
  } );

  const [ activeTab, setActiveTab ] = useState<'code' | 'tests'>( 'code' );
  const [ isTyping, setIsTyping ] = useState( false );
  const [ prompt, setPrompt ] = useState( '' );

  const addLog = useCallback( ( message: string, source: AgentRole | 'system', type: LogEntry[ 'type' ] = 'info' ) =>
  {
    const newLog: LogEntry = {
      id: Math.random().toString( 36 ).substr( 2, 9 ),
      timestamp: Date.now(),
      source,
      message,
      type,
    };
    setState( prev => ( { ...prev, logs: [ ...prev.logs, newLog ] } ) );
  }, [] );

  const addMessage = useCallback( ( text: string, role: 'user' | 'model' ) =>
  {
    const newMessage: ChatMessage = {
      id: Math.random().toString( 36 ).substr( 2, 9 ),
      role,
      text,
      timestamp: Date.now(),
    };
    setState( prev => ( { ...prev, messages: [ ...prev.messages, newMessage ] } ) );
  }, [] );

  const runSimulation = async ( inputPrompt: string ) =>
  {
    if ( !inputPrompt ) return;

    setState( prev => ( { ...prev, status: 'running', iteration: prev.iteration + 1 } ) );
    addLog( `Starting swarm for prompt: "${ inputPrompt }"`, 'system' );

    try
    {
      // 1. Planner Agent
      setState( prev => ( { ...prev, activeAgent: 'planner' } ) );
      addLog( "Analyzing requirements and planning architecture...", "planner" );
      const plan = await ai.generateProjectPlan( inputPrompt );
      addLog( `Plan generated: ${ plan.files.length } files identified.`, "planner", "success" );

      // 2. Designer Agent
      setState( prev => ( { ...prev, activeAgent: 'designer' } ) );
      addLog( "Generating design system and visual tokens...", "designer" );
      const theme = await ai.generateDesignSystem( inputPrompt );
      addLog( `Design system created: ${ theme.metadata.styleVibe } style.`, "designer", "success" );

      // 3. Coder Agent
      setState( prev => ( { ...prev, activeAgent: 'coder' } ) );
      addLog( "Implementing core logic in App.tsx...", "coder" );
      const code = await ai.generateCode( inputPrompt, plan, theme );
      setState( prev => ( { ...prev, codeContent: code } ) );
      addLog( "Code implementation complete.", "coder", "success" );

      // 4. Compiler Agent
      setState( prev => ( { ...prev, activeAgent: 'compiler' } ) );
      addLog( "Compiling React code to executable HTML...", "compiler" );
      const html = await ai.compileToHtml( code );
      setState( prev => ( { ...prev, previewContent: html, status: 'completed', activeAgent: 'idle' } ) );
      addLog( "Build successful! Preview ready.", "compiler", "success" );

    } catch ( error: any )
    {
      addLog( `Simulation failed: ${ error.message }`, 'system', 'error' );
      setState( prev => ( { ...prev, status: 'error', activeAgent: 'idle' } ) );
    }
  };

  const handleSendMessage = async ( text: string ) =>
  {
    addMessage( text, 'user' );
    setIsTyping( true );

    try
    {
      const response = await ai.chatWithAI( state.messages, text, state.codeContent );
      addMessage( response, 'model' );
    } catch ( error: any )
    {
      addLog( `Assistant error: ${ error.message }`, 'system', 'error' );
    } finally
    {
      setIsTyping( false );
    }
  };

  const handleGenerateTests = async ( options: { type: 'unit' | 'integration' | 'tdd', targetCoverage?: number, functionName?: string } ) =>
  {
    addLog( `Generating ${ options.type } tests...`, 'system' );
    try
    {
      const testCode = await ai.generateTests( state.codeContent, options.type, {
        functionName: options.functionName,
        targetCoverage: options.targetCoverage
      } );
      addLog( "Test suite generated and added to project.", 'system', 'success' );
    } catch ( error: any )
    {
      addLog( `Test generation failed: ${ error.message }`, 'system', 'error' );
    }
  };

  // Error capturing for self-healing
  useEffect( () =>
  {
    const handleMessage = async ( event: MessageEvent ) =>
    {
      if ( event.data.type === 'PREVIEW_ERROR' && state.status !== 'running' )
      {
        const errorMsg = event.data.message;
        addLog( `Runtime error detected: ${ errorMsg }. Triggering Patcher...`, 'system', 'warning' );

        setState( prev => ( { ...prev, activeAgent: 'patcher', status: 'running' } ) );
        try
        {
          const fixedCode = await ai.fixCode( state.codeContent, errorMsg );
          setState( prev => ( { ...prev, codeContent: fixedCode } ) );
          addLog( "Patcher fixed the code. Re-compiling...", 'patcher', 'success' );

          const html = await ai.compileToHtml( fixedCode );
          setState( prev => ( { ...prev, previewContent: html, status: 'completed', activeAgent: 'idle' } ) );
          addLog( "Self-healing successful!", 'compiler', 'success' );
        } catch ( err: any )
        {
          addLog( `Patcher failed: ${ err.message }`, 'patcher', 'error' );
          setState( prev => ( { ...prev, status: 'error', activeAgent: 'idle' } ) );
        }
      }
    };

    window.addEventListener( 'message', handleMessage );
    return () => window.removeEventListener( 'message', handleMessage );
  }, [ state.codeContent, state.status, addLog ] );

  return (
    <div className="flex h-screen bg-[#09090b] text-zinc-100 overflow-hidden font-sans antialiased">
      {/* Sidebar - Navigation & File Explorer */ }
      <aside className="w-64 border-r border-zinc-800 flex flex-col bg-[#0c0a09]">
        <div className="p-6 flex items-center gap-3">
          <div className="w-8 h-8 rounded-lg bg-blue-600 flex items-center justify-center shadow-[0_0_15px_rgba(37,99,235,0.4)]">
            <Cpu size={ 20 } className="text-white" />
          </div>
          <span className="text-xl font-bold tracking-tight">STUDIO <span className="text-blue-500">PRO</span></span>
        </div>

        <div className="flex-1 overflow-hidden">
          <FileExplorer files={ state.files } activeFile={ state.currentFile } />
        </div>

        <div className="p-4 border-t border-zinc-800">
          <div className="flex items-center gap-3 px-3 py-2 text-zinc-400 hover:text-zinc-100 cursor-pointer text-sm">
            <Settings size={ 18 } />
            <span>Settings</span>
          </div>
        </div>
      </aside>

      {/* Main Workspace */ }
      <main className="flex-1 flex flex-col overflow-hidden">
        {/* Header */ }
        <header className="h-16 border-b border-zinc-800 flex items-center justify-between px-6 bg-[#0c0a09]/80 backdrop-blur-md sticky top-0 z-50">
          <div className="flex items-center gap-4 flex-1 max-w-2xl">
            <div className="relative flex-1 group">
              <div className="absolute inset-y-0 left-4 flex items-center pointer-events-none text-zinc-500 group-focus-within:text-blue-500 transition-colors">
                <Sparkles size={ 18 } />
              </div>
              <input
                className="w-full bg-[#18181b] border border-zinc-800 rounded-full pl-12 pr-24 py-2 text-sm text-zinc-200 outline-none focus:border-blue-500/50 transition-all placeholder:text-zinc-600"
                placeholder="What would you like to build today?"
                value={ prompt }
                onChange={ ( e ) => setPrompt( e.target.value ) }
                onKeyDown={ ( e ) => e.key === 'Enter' && runSimulation( prompt ) }
              />
              <button
                onClick={ () => runSimulation( prompt ) }
                disabled={ state.status === 'running' || !prompt.trim() }
                className="absolute right-1.5 top-1.5 bottom-1.5 px-4 bg-blue-600 hover:bg-blue-500 disabled:bg-zinc-800 disabled:text-zinc-600 rounded-full text-xs font-black text-white transition-all flex items-center gap-2"
              >
                { state.status === 'running' ? 'WORKING...' : 'BUILD' }
              </button>
            </div>
          </div>

          <div className="flex items-center gap-4 ml-8">
            <AgentStatus activeAgent={ state.activeAgent } status={ state.status } />

            <div className="h-8 w-px bg-zinc-800" />

            <button className="p-2 hover:bg-zinc-800 rounded-lg text-zinc-400 transition-colors relative">
              <Bell size={ 18 } />
              <span className="absolute top-2 right-2 w-1.5 h-1.5 bg-blue-500 rounded-full"></span>
            </button>

            <div className="flex items-center gap-3 pl-4 border-l border-zinc-800">
              <div className="w-8 h-8 rounded-full bg-gradient-to-tr from-blue-500 to-indigo-500 flex items-center justify-center p-[1px]">
                <div className="w-full h-full rounded-full bg-zinc-900 flex items-center justify-center overflow-hidden">
                  <img src="https://api.dicebear.com/7.x/avataaars/svg?seed=ProDeveloper" alt="avatar" />
                </div>
              </div>
            </div>
          </div>
        </header>

        {/* Content Tabs Area */ }
        <div className="flex flex-col flex-1 p-4 gap-4 overflow-hidden">
          <div className="flex items-center gap-2">
            <button
              onClick={ () => setActiveTab( 'code' ) }
              className={ `flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${ activeTab === 'code' ? 'bg-blue-600 text-white' : 'bg-zinc-900 text-zinc-400 border border-zinc-800 hover:border-zinc-700' }` }
            >
              <Code2 size={ 14 } />
              Editor
            </button>
            <button
              onClick={ () => setActiveTab( 'tests' ) }
              className={ `flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${ activeTab === 'tests' ? 'bg-blue-600 text-white' : 'bg-zinc-900 text-zinc-400 border border-zinc-800 hover:border-zinc-700' }` }
            >
              <FlaskConical size={ 14 } />
              Tests
            </button>
          </div>

          <div className="flex-1 flex gap-4 overflow-hidden">
            {/* Center Panel */ }
            <div className="flex-1 bg-[#18181b] rounded-3xl border border-zinc-800 overflow-hidden shadow-2xl">
              { activeTab === 'code' ? (
                <CodeEditor
                  content={ state.codeContent }
                  fileName={ state.currentFile }
                  activeAgent={ state.activeAgent }
                  onChange={ ( val ) => setState( prev => ( { ...prev, codeContent: val } ) ) }
                />
              ) : (
                <TestGenerator
                  codeContent={ state.codeContent }
                  onGenerateTests={ handleGenerateTests }
                />
              ) }
            </div>

            {/* Preview Panel */ }
            <div className="flex-1 bg-[#18181b] rounded-3xl border border-zinc-800 overflow-hidden shadow-2xl">
              <Preview
                url={ state.previewUrl }
                isReady={ state.status === 'completed' || !!state.previewContent }
                activeAgent={ state.activeAgent }
                previewContent={ state.previewContent }
              />
            </div>
          </div>

          {/* Terminal Area */ }
          <div className="h-72 bg-[#18181b] rounded-3xl border border-zinc-800 shadow-2xl overflow-hidden mt-auto">
            <Terminal
              logs={ state.logs }
              messages={ state.messages }
              onSendMessage={ handleSendMessage }
              isTyping={ isTyping }
            />
          </div>
        </div>
      </main>
    </div>
  );
}

export default App;
