/**
 * Project Manager - Handle project creation and management
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Get home directory safely with fallback
const HOME_DIR = process.env.HOME || process.env.USERPROFILE || '/tmp';
const PROJECTS_DIR = path.join(HOME_DIR, '.agentic', 'projects');

/**
 * Validate that a path is safe and within expected boundaries
 */
function validatePath(userPath) {
  // Prevent path traversal attacks
  if (userPath.includes('..') || userPath.includes('~')) {
    throw new Error('Invalid path: path traversal not allowed');
  }
  
  // Ensure path doesn't start with /
  if (path.isAbsolute(userPath)) {
    throw new Error('Invalid path: absolute paths not allowed');
  }
  
  return true;
}

/**
 * Ensure projects directory exists
 */
async function ensureProjectsDir() {
  await fs.mkdir(PROJECTS_DIR, { recursive: true });
}

/**
 * Create a new project
 */
export async function createProject(options) {
  const { name, template } = options;
  
  if (!name) {
    throw new Error('Project name is required');
  }
  
  // Validate project name for security
  validatePath(name);
  
  await ensureProjectsDir();
  
  const projectPath = path.join(PROJECTS_DIR, name);
  
  // Check if project already exists
  try {
    await fs.access(projectPath);
    throw new Error(`Project "${name}" already exists`);
  } catch (error) {
    if (error.code !== 'ENOENT') throw error;
  }
  
  // Create project directory
  await fs.mkdir(projectPath, { recursive: true });
  
  // Create project structure based on template
  const structure = getTemplateStructure(template);
  
  for (const [filePath, content] of Object.entries(structure)) {
    const fullPath = path.join(projectPath, filePath);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, content, 'utf-8');
  }
  
  // Create project metadata
  const metadata = {
    name,
    template,
    createdAt: new Date().toISOString(),
    version: '1.0.0'
  };
  
  await fs.writeFile(
    path.join(projectPath, '.agentic.json'),
    JSON.stringify(metadata, null, 2),
    'utf-8'
  );
  
  return {
    name,
    path: projectPath,
    template
  };
}

/**
 * Load an existing project
 */
export async function loadProject(projectName) {
  const projectPath = path.join(PROJECTS_DIR, projectName);
  
  try {
    const metadataPath = path.join(projectPath, '.agentic.json');
    const metadata = JSON.parse(await fs.readFile(metadataPath, 'utf-8'));
    
    return {
      ...metadata,
      path: projectPath
    };
  } catch (error) {
    throw new Error(`Project "${projectName}" not found`);
  }
}

/**
 * List all projects
 */
export async function listProjects() {
  await ensureProjectsDir();
  
  const entries = await fs.readdir(PROJECTS_DIR, { withFileTypes: true });
  const projects = [];
  
  for (const entry of entries) {
    if (entry.isDirectory()) {
      try {
        const project = await loadProject(entry.name);
        const stats = await fs.stat(path.join(PROJECTS_DIR, entry.name));
        
        projects.push({
          ...project,
          lastModified: stats.mtime.toLocaleDateString()
        });
      } catch (error) {
        // Skip invalid projects
      }
    }
  }
  
  return projects;
}

/**
 * Get template structure
 */
function getTemplateStructure(template) {
  const templates = {
    react: {
      'package.json': JSON.stringify({
        name: 'agentic-react-app',
        version: '1.0.0',
        type: 'module',
        scripts: {
          dev: 'vite',
          build: 'vite build',
          test: 'jest'
        },
        dependencies: {
          react: '^18.2.0',
          'react-dom': '^18.2.0'
        },
        devDependencies: {
          '@vitejs/plugin-react': '^4.0.0',
          vite: '^4.0.0',
          jest: '^29.0.0'
        }
      }, null, 2),
      'src/App.tsx': `import React from 'react';

export default function App() {
  return (
    <div>
      <h1>Agentic React App</h1>
      <p>Built with AI-powered development</p>
    </div>
  );
}`,
      'src/main.tsx': `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`,
      'index.html': `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agentic App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`,
      'README.md': '# Agentic React App\n\nGenerated by Agentic Studio CLI\n\n## Development\n\n```bash\nnpm install\nnpm run dev\n```'
    },
    node: {
      'package.json': JSON.stringify({
        name: 'agentic-node-app',
        version: '1.0.0',
        type: 'module',
        scripts: {
          start: 'node src/index.js',
          dev: 'node --watch src/index.js',
          test: 'jest'
        },
        dependencies: {
          express: '^4.18.0'
        },
        devDependencies: {
          jest: '^29.0.0'
        }
      }, null, 2),
      'src/index.js': `import express from 'express';

const app = express();
const port = process.env.PORT || 3000;

app.get('/', (req, res) => {
  res.json({ message: 'Agentic Node App' });
});

app.listen(port, () => {
  console.log(\`Server running on port \${port}\`);
});`,
      'README.md': '# Agentic Node App\n\nGenerated by Agentic Studio CLI\n\n## Development\n\n```bash\nnpm install\nnpm run dev\n```'
    },
    fullstack: {
      'package.json': JSON.stringify({
        name: 'agentic-fullstack-app',
        version: '1.0.0',
        type: 'module',
        scripts: {
          dev: 'concurrently "npm run dev:server" "npm run dev:client"',
          'dev:server': 'node --watch server/index.js',
          'dev:client': 'vite',
          build: 'vite build',
          test: 'jest'
        },
        dependencies: {
          express: '^4.18.0',
          react: '^18.2.0',
          'react-dom': '^18.2.0'
        },
        devDependencies: {
          '@vitejs/plugin-react': '^4.0.0',
          vite: '^4.0.0',
          concurrently: '^8.0.0',
          jest: '^29.0.0'
        }
      }, null, 2),
      'server/index.js': `import express from 'express';

const app = express();
const port = 3001;

app.use(express.json());

app.get('/api/health', (req, res) => {
  res.json({ status: 'ok' });
});

app.listen(port, () => {
  console.log(\`API server running on port \${port}\`);
});`,
      'src/App.tsx': `import React from 'react';

export default function App() {
  return (
    <div>
      <h1>Agentic Fullstack App</h1>
    </div>
  );
}`,
      'README.md': '# Agentic Fullstack App\n\nGenerated by Agentic Studio CLI\n'
    }
  };
  
  return templates[template] || templates.react;
}
